Repository kumuluz/kumuluzee, pull requests merged in 2018-08, with the labels that each got.

#108 Added method isEnabled to the Extension interface
  common/src/main/java/com/kumuluz/ee/common/Extension.java
  core/src/main/java/com/kumuluz/ee/EeApplication.java
Labels: Feature

#109 Added config property to enable Jetty startup exception propagation
  common/src/main/java/com/kumuluz/ee/common/config/ServerConfig.java
  core/src/main/java/com/kumuluz/ee/factories/EeConfigFactory.java
  servlet/jetty/src/main/java/com/kumuluz/ee/jetty/JettyServletServer.java
Labels: Feature

#110 Enhancement/dependency upgrade
  pom.xml
Labels: enhancement

#113 Added bean validation CDI integration
  components/bean-validation/hibernate-validator/pom.xml
Labels: enhancement

#114 Added transaction manager to JNDI
  common/pom.xml
  common/src/main/java/com/kumuluz/ee/common/ServletServer.java
  components/jta/narayana/src/main/java/com/kumuluz/ee/jta/narayana/JtaComponent.java
  servlet/jetty/src/main/java/com/kumuluz/ee/jetty/JettyServletServer.java
Labels: enhancement

#111 Fix stopServer method throwing IllegalStateException
  servlet/jetty/src/main/java/com/kumuluz/ee/jetty/JettyServletServer.java
Labels: bug

#116 Added support for Java 10 to various components
  components/jax-rs/jersey/pom.xml
  components/jax-ws/cxf/pom.xml
  components/jax-ws/metro/pom.xml
  components/jpa/hibernate/pom.xml
  pom.xml
Labels: enhancement
